diver/diver/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from diver import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.main, name='main'),
    url(r'^upload/$', views.upload),
    url(r'^upload_item/$', views.upload_item),
    url(r'^search/$', views.search),
    url(r'^auth/$', views.auth),
    url(r'^like/([0-9]+)$',views.like),
    url(r'^match_like/([0-9]+)/([0-9]+)$',views.match_like),
    url(r'^account/$', views.account),
    url(r'^hanger/$', views.hanger),
    url(r'^update_hanger/$', views.update_hanger, name="update_hanger"),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
]

diver/diver/models.py
from django.db import models


def lookup_code(mapping):
    def lookup(name):
        for c,s in mapping:
            if type(s) is tuple:
                for k,v in s:
                    if v.strip().lower() == name.strip().lower(): return k
            else:
                if s.strip().lower() == name.strip().lower(): return c
    return lookup

class ItemPref(models.Model):
    customer = models.ForeignKey('Customer', null=True)
    item = models.ForeignKey('Item', null=True)
    score = models.IntegerField()

class Customer(models.Model):
    # Basic authentication information
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=128)
    user = models.ForeignKey('auth.User')

    # Body dimensions
    height_cm = models.FloatField()
    weight_kg = models.FloatField()
    chest_size_cm = models.FloatField()
    waist_size_cm = models.FloatField()
    ########
    sleeve_length_cm = models.IntegerField(null=True)

    leg_length_cm = models.FloatField()
    shoes_size_mm = models.FloatField()
    hip_cm = models.FloatField(null=True)
    thigh_cm = models.FloatField(null=True)

    BODY_SHAPES = (
        ('O', 'Abdominal obese'),
        ('M', 'Muscular'),
        ('A', 'Skinny'),
        ('B', 'Fat'),
        ('N', 'Normal'),
    )
    body_shape = models.CharField(max_length=1, choices=BODY_SHAPES)
    get_body_shape_code = lookup_code(BODY_SHAPES)

    def like(item, score):
        pass

    def dislike(item):
        pass

    def modify_score(recommendation):
        pass


class Image(models.Model):
    filename = models.CharField(max_length=30)
    image = models.ImageField(null=True)

class Item(models.Model):
    name = models.CharField(max_length=30)

    # List of types.
    TYPES = (
        (0, "TOP"),
        (1, "OUTER"),
        (2, "BOTTOM"),
        (3, "SHOES"),
    )
    type = models.IntegerField(choices=TYPES)
    get_type_code = lookup_code(TYPES)

    # List of categories.
    # Category code should not be longer than 10 chars.
    CATEGORIES = (
        ("Top", (
            ('SHIRT', "Shirt"),
            ('TSHIRT', "T-shirt"),
            ('SLEEVELESS', "Sleeveless"),
            ('KNIT', "Knit"),
            ('HOOD', "Hood"),
            ('CREW', "Crew sweatshirt"),
        )),
        ("Outer", (
            ('STJP', "Stadium jumper"),
            ('BLOUSON', "Blouson"),
            ('JUMPER', "Jumper"),
            ('JACKET', "Jacket"),
            ('COAT', "Coat"),
            ('VEST', "Vest"),
            ('DENIM', "Denim"),
            ('CARDIGAN', "Cardigan"),
        )),
        ("Bottom", (
            ('JEAN', "Jean"),
            ('COTTON', "Cotton"),
            ('SLACKS', "Slacks"),
            ('JOGGER', "Jogger"),
            ('BAGGY', "Baggy"),
        )),
    )
    category = models.CharField(max_length=10, choices=CATEGORIES)
    get_category_code = lookup_code(CATEGORIES)
    @staticmethod
    def get_category1(category):
        for category1 in Item.CATEGORIES:
            for category2 in category1[1]:
                if category.upper() == category2[0].upper():
                    return category1[0]
    def category1(self):
        return Item.get_category1(self.category)

    # List of materials.
    # Material code should be 2 chars.
    MATERIALS = (
        ('AC', "Acrylic"),
        ('CD', "Corduroy"),
        ('CT', "Cotton"),
        ('LN', "Linen"),
        ('NP', "Neoprene"),
        ('OX', "Oxford"),
        ('PG', "Pigment"),
        ('PL', "Poly"),
        ('SL', "Slub"),
        ('TW', "Tweed"),
        ('WL', "Wool"),
        ('DN', "Denim"),
        ('LT', "Leather"),
        ('NL', "Nylon"),
    )
    material = models.CharField(max_length=2, choices=MATERIALS)
    get_material_code = lookup_code(MATERIALS)

    # List of patterns.
    # Pattern code should be 2 chars.
    PATTERNS = (
        ('CM', 'Camoflage'),
        ('CH', 'Checked'),
        ('FL', 'Floral'),
        ('GR', 'Gradation'),
        ('MC', 'Multicolors'),
        ('NO', 'None'),
        ('PR', 'Printed'),
        ('SF', 'Snowflake'),
        ('ST', 'Striped'),
        ('TW', 'Twisted'),
        ('VS', 'Vertical'),
    )
    pattern = models.CharField(max_length=2, choices=PATTERNS)
    get_pattern_code = lookup_code(PATTERNS)


    price = models.IntegerField()
    images = models.URLField()
    comment = models.TextField()
    purchase_url = models.URLField()

    rate_count = models.IntegerField(default=0)

    # For Top
    sleeve_level = models.IntegerField(null=True)
    NECK_TYPES = (
        ('RN', "Round"),
        ('HR', "Henry"),
        ('HT', "Hat"),
        ('VN', "V-Neck"),
        ('ST', "Stripe"),
        ('TT', "Turtle"),
        ('CL', "Collar"),
        ('CH', "Chinese"),
    )
    neck = models.CharField(max_length=2, choices=NECK_TYPES, null=True)
    get_neck_code = lookup_code(NECK_TYPES)
    zipper = models.IntegerField(null=True)
    button = models.IntegerField(null=True)

    # For Outer
    ## sleeve_level
    ## zipper
    length_level = models.IntegerField(null=True)
    collar = models.IntegerField(null=True)
    hat = models.IntegerField(null=True)
    # button = models.IntegerField(null=True)
    padding = models.IntegerField(null=True)

    # For Bottom
    ## length_level
    FIT_TYPES = (
        ('ST', "Straight"),
        ('SL', "Slim"),
        ('BG', "Baggy"),
        ('SK', "Skinny"),
        ('WD', "Wide"),
        ('TP', "Tapered"),
    )
    fit = models.CharField(max_length=2, choices=FIT_TYPES, null=True)
    get_fit_code = lookup_code(FIT_TYPES)
    jean_washing = models.IntegerField(null=True)

    # For Shoes
    weight_g = models.IntegerField(null=True)
    insoles = models.IntegerField(null=True)
    brand = models.CharField(max_length=100, null=True)

    #shop = models.ForeignKey(through = 'Shop')

class Color(models.Model):
    item = models.ForeignKey('Item')
    COLOR_VALUES = (
        (0, (0xF5, 0xF5, 0xDC)),
        (1, (0x00, 0x00, 0x00)),
        (2, (0x00, 0x00, 0xFF)),
        (3, (0xA5, 0x2A, 0x2A)),
        (4, (0xFF, 0xD7, 0x00)),
        (5, (0x00, 0x80, 0x00)),
        (6, (0x80, 0x80, 0x80)),
        (7, (0xF0, 0xF6, 0x8C)),
        (8, (0xF5, 0xFF, 0xFA)),
        (9, (0x00, 0x00, 0x80)),
        (10,(0xFF, 0xA5, 0x00)),
        (11,(0xFF, 0xC0, 0xCB)),
        (12,(0xFF, 0x00, 0x00)),
        (13,(0x87, 0xCE, 0xEB)),
        (14,(0xFF, 0xFF, 0xFF)),
        (15,(0xFF, 0xFF, 0x00)),
        (16,(0xA9, 0xA9, 0xA9)),
        (17,(0xFF, 0xFF, 0xF0)),
        (18,(0x80, 0x00, 0x80)),
        (19,(0x00, 0x64, 0x00)),
    )
    COLORS = (
        (0, "Beige"),
        (1, "Black"),
        (2, "Blue"),
        (3, "Brown"),
        (4, "Gold"),
        (5, "Green"),
        (6, "Grey"),
        (7, "Khaki"),
        (8, "Mint"),
        (9, "Navy"),
        (10, "Orange"),
        (11, "Pink"),
        (12, "Red"),
        (13, "Skyblue"),
        (14, "White"),
        (15, "Yellow"),
        (16, "Charcoal"),
        (17, "Ivory"),
        (18, "Purple"),
        (19, "Dark green"),
    )
    get_color_code = lookup_code(COLORS)
    color_id1 = models.SmallIntegerField(choices=COLORS)
    color_id2 = models.SmallIntegerField(choices=COLORS, null=True)
    color_id3 = models.SmallIntegerField(choices=COLORS, null=True)
    color_ratio1 = models.SmallIntegerField()
    color_ratio2 = models.SmallIntegerField()
    color_ratio3 = models.SmallIntegerField()

class Size(models.Model):
    item = models.ForeignKey('Item')

    # For Top
    length_cm = models.IntegerField(null=True)
    shoulder_cm = models.IntegerField(null=True)
    chest_cm = models.IntegerField(null=True)
    sleeve_cm = models.IntegerField(null=True)
    letter = models.CharField(max_length=5, null=True)

    # For Outer
    ## Shares attributes with Top

    # For Bottom
    ## length_cm
    waist_cm = models.IntegerField(null=True)
    thigh_cm = models.IntegerField(null=True)
    crotch_cm = models.IntegerField(null=True)
    ## letter

    # For Shoes
    size_mm = models.IntegerField(null=True)
    correction = models.IntegerField(null=True)

class Match(models.Model):
    image = models.URLField()
    rate_count = models.IntegerField(default=0)
    url = models.URLField()
    outer1 = models.ForeignKey('Color', related_name='match_for_outer1', null=True)
    outer2 = models.ForeignKey('Color', related_name='match_for_outer2', null=True)
    top1 = models.ForeignKey('Color', related_name='match_for_top1', null=True)
    top2 = models.ForeignKey('Color', related_name='match_for_top2', null=True)
    bottom = models.ForeignKey('Color', related_name='match_for_bottom', null=True)
    shoes = models.ForeignKey('Color', related_name='match_for_shoes', null=True)

class Shop(models.Model):
    name = models.CharField(max_length=30)
    url = models.URLField()
    items = models.ManyToManyField(Item)
    matches = models.ManyToManyField('Match')
    rate_count = models.IntegerField()

class Rating(models.Model):
    customer = models.ForeignKey('Customer')
    match = models.ForeignKey('Match', null=True)

    def score_range_validator(score):
        if not (-2 <= score <= 2):
            raise ValidationError("Rating should be between -2 and 2, inclusively.")
    score = models.SmallIntegerField(default=0, validators=[score_range_validator])

class Pref(models.Model):
    customer = models.ForeignKey(Customer)
    pattern_CM = models.IntegerField(default=0)
    pattern_CH = models.IntegerField(default=0)
    pattern_FL = models.IntegerField(default=0)
    pattern_GR = models.IntegerField(default=0)
    pattern_LG = models.IntegerField(default=0)
    pattern_MC = models.IntegerField(default=0)
    pattern_NO = models.IntegerField(default=0)
    pattern_PR = models.IntegerField(default=0)
    pattern_SF = models.IntegerField(default=0)
    pattern_ST = models.IntegerField(default=0)
    pattern_TW = models.IntegerField(default=0)
    pattern_VS = models.IntegerField(default=0)

diver/diver/templates/account.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<h1>당신에 대해 알려주세요 ( ͡° ͜ʖ ͡°)</h1>
<form method="post">
{% csrf_token %}
<div class="row">
  <h1>필수 정보</h1>
  <div class="form-group col-md-3">
    <label for="weight">몸무게(kg)</label>
    <input name= "weight_kg" id="weight" type="number" class="form-control"
      {% if customer %}value={{customer.weight_kg}}{% endif %}>
  </div>
  <div class="form-group col-md-3">
    <label for="height">키(cm)</label>
    <input name="height_cm" id="height" type="number" class="form-control"
      {% if customer %}value={{customer.height_cm}}{% endif %}>
  </div>
  <div class="form-group col-md-6">
    <label for="body_shape">체형</label>
    <select name="body_shape" class="form-control" id="body_shape">
      <option value="O"{% if customer.body_shape == 'O'%} selected{% endif %}>Abdominal obese</option>
      <option value="M"{% if customer.body_shape == 'M'%} selected{% endif %}>Muscular</option>
      <option value="A"{% if customer.body_shape == 'A'%} selected{% endif %}>Skinny</option>
      <option value="B"{% if customer.body_shape == 'B'%} selected{% endif %}>Fat</option>
      <option value="N"{% if customer.body_shape == 'N'%} selected{% endif %}>Normal</option>
    </select>
  </div>
</div>
<div class="row">
  <h1>선택 정보</h1>
  <div class="form-group col-md-2">
    <label for="chest">가슴 둘레(cm)</label>
    <input name="chest_size_cm" id="chest" type="number" class="form-control"
      {% if customer.chest_size_cm != 0 %}value={{customer.chest_size_cm|floatformat:1 }}{% endif %}>
  </div>
  <div class="form-group col-md-2">
    <label for="waist">허리 둘레(cm)</label>
    <input name="waist_size_cm" id="waist" type="number" class="form-control"
      {% if customer.waist_size_cm != 0 %}value={{customer.waist_size_cm|floatformat}}{% endif %}>
  </div>

  <div class="form-group col-md-3">
    <label for="leg">다리 길이(cm)</label>
    <input name="leg_length_cm" id="leg" type="number" class="form-control"
      {% if customer.leg_length_cm != 0 %}value={{customer.leg_length_cm|floatformat }}{% endif %}>
  </div>

  <div class="form-group col-md-3">
    <label for="leg">엉덩이 둘레(cm)</label>
    <input name="hip_cm" id="hip" type="number" class="form-control"
      {% if customer.hip_cm != 0 %}value={{customer.hip_cm|floatformat }}{% endif %}>
  </div>

  <div class="form-group col-md-3">
    <label for="leg">허벅지 둘레(cm)</label>
    <input name="thigh_cm" id="thigh" type="number" class="form-control"
      {% if customer.thigh_cm != 0 %}value={{customer.thigh_cm|floatformat }}{% endif %}>
  </div>

  <div class="form-group col-md-3">
    <label for="shoes">신발 사이즈(mm)</label>
    <input name="shoes_size_mm" id="shoes" type="number" class="form-control"
      {% if customer.shoes_size_mm != 0 %}value={{customer.shoes_size_mm|floatformat }}{% endif %}>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-xs-12 col-lg-12">
    <input class="btn btn-default" type="submit" name="survey"/>
  </div>
</div>
</form>
{% if not customer %}
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <img src="{% static 'images/welcome.jpg' %}" alt="환영합니다!">
        <h3>다입어에 오신 것을 환영합니다.</h3>
        <p>먼저, 저희가 여러분에 대해 알 수 있게 기본적인 정보와 취향을
        알려주세요!</p>
        <p>놀라지 마세요. 신체정보는 키와 몸무게, 체형만으로 충분합니다.</p>
        <p>물론 더 많은 정보를 입력하시면 더 정확한 추천결과를 받아볼 수
        있어요!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"
          data-dismiss="modal">알겠습니다 :P</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endif %}
<script>
$('.modal').modal('show');
</script>
{% endblock %}

diver/diver/templates/auth.html
{% extends 'base.html' %}
{% block styletags %}
<style>
  .btn-social {
    margin-bottom: 1em;
  }
</style>
{% endblock %}
{% block content %}
{% if user and not user.is_anonymous %}
<h1>My Diver</h1>
 <p>Hello {{ user.get_full_name|default:user.username }}!</p>
 <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
{% else %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Login with social accounts</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"
    class="btn btn-block btn-social btn-facebook">
        <i class="fa fa-facebook"></i> Sign in with Facebook
    </a>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}"
    class="btn btn-block btn-social btn-google">
        <i class="fa fa-google"></i> Sign in with Google
    </a>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"
    class="btn btn-block btn-social btn-twitter">
        <i class="fa fa-twitter"></i> Sign in with Twitter
    </a>
  </div>
</div>
{% endif %}
{% endblock %}

diver/diver/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Diver - Fashion Recommendation for You</title>
  <meta name="description" content="Diver">
  <meta name="author" content="FashionKing">

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/earlyaccess/jejugothic.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-social.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.2/toastr.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/stars.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  <link rel="icon" href="{% static 'images/hanger.png' %}">

  <style type="text/css">
    .main.container {
      padding-bottom: 20px;
      }
    img.logo {
      height: 4em;
    }
  </style>
  {% block styletags %}{% endblock %}
  <script type="text/javascript" src="{% static 'javascript/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'javascript/jquery-ui.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'javascript/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'javascript/multifile.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.2/toastr.min.js"></script>
  {% block head %}{% endblock %}
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-header">
          <a href="/">
          <img src="{% static 'images/logo.png' %}" alt="logo" class="logo">
          </a>
        </div>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li><a href="/search">추천 받기</a></li>
          <li><a href="/upload">코디 업로드</a></li>
          <li><a href="/upload_item">아이템 업로드</a></li>

        <ul class="nav navbar-nav navbar-right">
          {% if user and not user.is_anonymous %}
            <li><a href="/account">My Diver</a></li>
            <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>

          {% else %}
            <li><a href="/auth">Sign in</a></li>
          {% endif %}
        </ul>

      </div>
    </div>
  </nav>
  <div class="main container">
    <section id="content">
      {% block content %}{% endblock %}
    </section>
  </div>
{% block script %}{% endblock %}
</body>
</div>
<hr />
<footer>
</footer>
</html>

diver/diver/templates/hanger.html
{% load item_filters %}
<div id="hanger-large" class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Hanger</h4>
    </div>
    <div class="modal-body">
      <div id="outer-slots" class="item-slots">
        <h3>Outer</h3>
        <div class="item-slot outer-slot">{% hanger_item_large hanger "OUTER" 0 %}</div>
        <div class="item-slot outer-slot">{% hanger_item_large hanger "OUTER" 1 %}</div>
      </div>
      <div id="top-slots" class="item-slots">
        <h3>Top</h3>
        <div class="item-slot top-slot">{% hanger_item_large hanger "TOP" 0 %}</div>
        <div class="item-slot top-slot">{% hanger_item_large hanger "TOP" 1 %}</div>
      </div>
      <div id="bottom-slots" class="item-slots">
        <h3>Bottom</h3>
        <div class="item-slot bottom-slot">{% hanger_item_large hanger "BOTTOM" 0 %}</div>
      </div>
      <div id="shoe-slots" class="item-slots">
        <h3>Shoes</h3>
        <div class="item-slot shoes-slot">{% hanger_item_large hanger "SHOE" 0 %}</div>
      </div>
      <div style="clear: both;"></div>
    </div>
  </div>
</div>

diver/diver/templates/hanger_item_large_template.html
<div class="hanger-item"{% if item %} data-item-id="{{ item.id }}"{% endif %}>
    {% if item %}
    <img src="{{ item.images }}"><div></div>
    <a href="{{ item.purchase_url }}" target="_blank">{{ item.name }} ({{ item.price }})</a>
    {% else %}
    <p>NO ITEM</p>
    {% endif%}
</div>

diver/diver/templates/hanger_item_small_template.html
<div class="hanger-item"{% if item %} data-item-id="{{ item.id }}"{% endif %}>
    {% if item %}
    <img src="{{ item.images }}">
    {% else %}
    <p>NO ITEM</p>
    {% endif%}
</div>

diver/diver/templates/hanger_item_template.html
<div class="hanger-item"{% if item %} data-item-id="{{ item.id }}"{% endif %}>
    {% if item %}
    <img src="{{ item.images }}">
    {% else %}
    <p>NO ITEM</p>
    {% endif%}
</div>

diver/diver/templates/item_card_template.html
{% if item %}
{% load item_filters %}
<div class="item {{ class_names }}"
    data-item-id="{{ item.id }}"
    data-item-category1="{{ item.category|category1 }}"
    data-item-category2="{{ item.category }}">
    <img src={{ item.images }}>
    <div class="item-colors col-md-12 col-xs-12 col-lg-12">
      {% if item.color_set.all %}
      {% for color in item.color_set.all %}
        <div class="item-color-combination">
          <div class="item-color" style="background-color: {{ color.color_id1|hex_code }}; height: {{ color.color_ratio1 }}%;"></div>
          {% if color.color_ratio2 != 0 %}
          <div class="item-color" style="background-color: {{ color.color_id2|hex_code }}; height: {{ color.color_ratio2 }}%;"></div>
          {% endif %}
          {% if color.color_ratio3 != 0 %}
          <div class="item-color" style="background-color: {{ color.color_id3|hex_code }}; height: {{ color.color_ratio3 }}%;"></div>
          {% endif %}
        </div>
      {% endfor %}
      {% else %}
        <div class="dummy-color-combination"></div>
      {% endif %}
    </div>
    <div class="col-md-12 col-xs-12 col-lg-12">
      <span class="star-rating">
        <input type="radio" name="rating{{item.id}}" value=1
                            {% if score == 1 %}checked{% endif %}
                            onclick="like({{item.id}}, 1)"><i></i>
        <input type="radio" name="rating{{item.id}}" value=2
                            {% if score == 2 %}checked{% endif %}
                            onclick="like({{item.id}}, 2)"><i></i>
        <input type="radio" name="rating{{item.id}}" value=3
                            {% if score == 3 %}checked{% endif %}
                            onclick="like({{item.id}}, 3)"><i></i>
        <input type="radio" name="rating{{item.id}}" value=4
                            {% if score == 4 %}checked{% endif %}
                            onclick="like({{item.id}}, 4)"><i></i>
        <input type="radio" name="rating{{item.id}}" value=5
                            {% if score == 5 %}checked{% endif %}
                            onclick="like({{item.id}}, 5)"><i></i>
      </span>
    </div>
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <a class="btn btn-link ellipsis" href="{{item.purchase_url}}"
          target="_blank">{{ item.name }}</a>
      </div>
      <div class="col-md-6 col-xs-6">
        <p class="btn btn-link">{{ item.price }}</p>
      </div>
      <div class="col-md-6 col-xs-6">
        <p class="button-to-hanger">
        <a class="btn btn-link" onclick="toHanger({{item.id}},
                    '{{item.category|category1}}',
                    '{{item.images}}')">To hanger</a>
        </p>
      </div>
    </div>
</div>
{% endif %}

diver/diver/templates/main.html
{% extends 'base.html' %}
{% block content %}
  {% load staticfiles %}
  <div class="jumbotron">
    <div class="container">
      <h1>DIVER</h1>

      <p>추천은 저희가 해 드립니다. 그냥 다 입으세요. 다 입어.</p>
      <p><a href="#" role="button" class="btn btn-default btn-lg">Learn more</a></p>
    </div>
  </div>
  <div class="container">
    <div class="row">
      {% load item_filters %}
      {% for match, score in pairs %}
        {% match_card match score "col-lg-3 col-md-3 col-xs-6"%}
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    function like(id, score) {
      $.ajax({
        'method': 'get',
        'dataType': 'text',
        'url': '/like/'+id+'/'+score,
        'success': function(res){
        },
        'error': function(request,status,error){
          console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        }
      });
    }
  </script>

  <script>
    function match_like(id, score) {
      $.ajax({
        'method': 'get',
        'dataType': 'text',
        'url': '/match_like/'+id+'/'+score,
        'success': function(res){
        },
        'error': function(request,status,error){
          console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        }
      });
    }
  </script>
{% endblock %}